-- Reset databases if they already exist
DROP DATABASE IF EXISTS prod;
DROP DATABASE IF EXISTS test;

-- ======================
-- PROD DATABASE
-- ======================
CREATE DATABASE prod;
USE prod;

CREATE TABLE parking(
  PARKING_NUMBER INT PRIMARY KEY,
  AVAILABLE BOOLEAN NOT NULL,
  TYPE VARCHAR(10) NOT NULL
);

CREATE TABLE ticket(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  PARKING_NUMBER INT NOT NULL,
  VEHICLE_REG_NUMBER VARCHAR(10) NOT NULL,
  PRICE DOUBLE,
  IN_TIME DATETIME NOT NULL,
  OUT_TIME DATETIME,
  FOREIGN KEY (PARKING_NUMBER)
    REFERENCES parking(PARKING_NUMBER)
);

INSERT INTO parking VALUES (1, true, 'CAR');
INSERT INTO parking VALUES (2, true, 'CAR');
INSERT INTO parking VALUES (3, true, 'CAR');
INSERT INTO parking VALUES (4, true, 'BIKE');
INSERT INTO parking VALUES (5, true, 'BIKE');

-- ======================
-- TEST DATABASE
-- ======================
CREATE DATABASE test;
USE test;

CREATE TABLE parking(
  PARKING_NUMBER INT PRIMARY KEY,
  AVAILABLE BOOLEAN NOT NULL,
  TYPE VARCHAR(10) NOT NULL
);

CREATE TABLE ticket(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  PARKING_NUMBER INT NOT NULL,
  VEHICLE_REG_NUMBER VARCHAR(10) NOT NULL,
  PRICE DOUBLE,
  IN_TIME DATETIME NOT NULL,
  OUT_TIME DATETIME,
  FOREIGN KEY (PARKING_NUMBER)
    REFERENCES parking(PARKING_NUMBER)
);

INSERT INTO parking VALUES (1, true, 'CAR');
INSERT INTO parking VALUES (2, true, 'CAR');
INSERT INTO parking VALUES (3, true, 'CAR');
INSERT INTO parking VALUES (4, true, 'BIKE');
INSERT INTO parking VALUES (5, true, 'BIKE');
